/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  workbench: () => import("@/views/Workbench/index.vue"),
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  business_repair: () => import("@/views/business/Repair/index.vue"),
  business_report: () => import("@/views/business/Report/index.vue"),
  custom_workbench: () => import("@/views/custom/workbench/index.vue"),
  emergency: () => import("@/views/emergency/index.vue"),
  historical: () => import("@/views/historical/index.vue"),
  home: () => import("@/views/home/index.vue"),
  management_community: () => import("@/views/management/community/index.vue"),
  management_component: () => import("@/views/management/component/index.vue"),
  management_equipment: () => import("@/views/management/equipment/index.vue"),
  management: () => import("@/views/management/index.vue"),
  management_knowledge: () => import("@/views/management/knowledge/index.vue"),
  management_maintenancegroup: () => import("@/views/management/maintenanceGroup/index.vue"),
  management_organizational: () => import("@/views/management/organizational/index.vue"),
  monitoring_demo: () => import("@/views/monitoring/demo/index.vue"),
  monitoring_detail: () => import("@/views/monitoring/detail/index.vue"),
  safetysystem_daily: () => import("@/views/safetySystem/Daily/index.vue"),
  safetysystem_archive: () => import("@/views/safetySystem/archive/index.vue"),
  safetysystem_checklist: () => import("@/views/safetySystem/checklist/index.vue"),
  safetysystem: () => import("@/views/safetySystem/index.vue"),
  safetysystem_managementpersonnel: () => import("@/views/safetySystem/managementPersonnel/index.vue"),
  safetysystem_monthcontrol: () => import("@/views/safetySystem/monthControl/index.vue"),
  safetysystem_training: () => import("@/views/safetySystem/training/index.vue"),
  safetysystem_weeklycontrol: () => import("@/views/safetySystem/weeklyControl/index.vue"),
  scheduling: () => import("@/views/scheduling/index.vue"),
  system_customworkbench: () => import("@/views/system/customWorkbench/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_operations: () => import("@/views/system/operations/index.vue"),
  system_person: () => import("@/views/system/person/index.vue"),
  system_roles: () => import("@/views/system/roles/index.vue"),
};
